# Generated by Django 2.1 on 2019-04-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0005_auto_20190422_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCustomer',
            fields=[
                ('customerID', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=10)),
                ('nation', models.CharField(max_length=10)),
                ('check_in_date', models.DateField()),
            ],
        ),
    ]
