# Generated by Django 2.1 on 2019-04-28 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check_out',
            fields=[
                ('customerID', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('check_out_type', models.CharField(max_length=20)),
                ('check_out_reason', models.TextField()),
                ('check_out_time', models.DateField()),
                ('check_out_state', models.BooleanField()),
                ('time', models.DateField()),
                ('remark', models.TextField()),
            ],
        ),
    ]
