# Generated by Django 2.1 on 2019-04-24 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('bedID', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('image', models.ImageField(height_field=100, upload_to='', width_field=100)),
                ('name', models.CharField(max_length=20)),
                ('nation', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=1)),
                ('age', models.IntegerField()),
                ('ID_number', models.CharField(max_length=20)),
                ('birthdate', models.DateField()),
                ('province', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=40)),
                ('marrige', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('remark', models.TextField()),
                ('phonenum1', models.CharField(max_length=11)),
                ('phonenum2', models.CharField(max_length=11)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('state_1', models.BooleanField()),
                ('state_2', models.BooleanField()),
                ('bedID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CustomerModel.Bed')),
            ],
        ),
    ]
